Merged NAMESPACE changes back onto HEAD

diff --git a/surfraw.IN b/surfraw.IN
--- a/surfraw.IN
+++ b/surfraw.IN
@@ -7,11 +7,12 @@
 #
 # see the file COPYING for further copyright details
 #
-# @configure_input@
 
 surfraw_version=@VERSION@
 surfraw_api_version=1.0
 w3_argv0=`basename "$0"`
+
+elvidir="@ELVIDIR@"
 
 # defaults
 
@@ -20,11 +21,11 @@ w3_config_hook () {
 }
 
 w3_config () {
-prefix=@prefix@
-def   SURFRAW_global_conf	@sysconfdir@/surfraw.conf
-def   SURFRAW_conf		$HOME/.surfraw.conf
+	prefix=@prefix@
+   def   SURFRAW_global_conf	@sysconfdir@/surfraw.conf
+   def   SURFRAW_conf		$HOME/.surfraw.conf
 
-    test -r "$SURFRAW_global_conf" || err "couldn't source SURFRAW_global_conf ($SURFRAW_global_conf)"
+	test -r "$SURFRAW_global_conf" || err "couldn't source SURFRAW_global_conf ($SURFRAW_global_conf)"
     . "$SURFRAW_global_conf"
     w3_config_hook
     test -r "$SURFRAW_conf" && . "$SURFRAW_conf"
@@ -100,6 +101,33 @@ setoptyn () {
     yesno "$1"
 }
 
+quote_ifs () {
+	 if [ -z "$1" ];   then return;  fi
+     perl -e '$ifs=$ENV{IFS} || " "; $arg=shift;if($arg =~/[$ifs]/) { $arg="\"$arg\""; } print "$arg\n"; ' "$1"
+}
+
+bookmark_file_search () {
+	search="$1"
+	file="$2"
+	if [ -f "$file" ]
+	then
+		awk -v search="$search" '$1 ~ search { print $2; }'  $file
+	fi
+}
+
+bookmark_lookup () {
+	search="$1"
+	lookup=`bookmark_file_search "$search" ~/.surfraw.bookmarks`
+	if [ -z "$lookup" ]
+	then
+		lookup=`bookmark_file_search "$search" /etc/surfraw.bookmarks`
+	fi
+	if [ -n "$lookup" ]
+	then
+		echo "$lookup"
+	fi
+}
+
 w3_find_prog () {
   prog="$1"
   old_ifs="${IFS:-\" \"}"
@@ -154,9 +182,9 @@ w3_url_of_arg () {
         args="$@"
     fi
     if ok SURFRAW_escape_url_args; then
-	w3_url_escape "$args"
+     	w3_url_escape "$args"
     else
-	echo "$@"
+	    echo "$args"
     fi
 }
 
@@ -175,7 +203,7 @@ w3_global_usage () {
 Global options:
   -browser=EXECUTABLE		Set browser
 				Default: $SURFRAW_browser
-  -elvi				List Surfraw mechanims for conquering evil
+  -elvi				List Surfraw mechanisms for conquering evil
   -escape-url-args=yes|no	Apply url escaping to arguments
 				Default: $SURFRAW_escape_url_args
 				Environment: SURFRAW_escape_url_args
@@ -198,6 +226,8 @@ Global options:
 				Environment: SURFRAW_quote_args
   -version			Display Surfraw version ($surfraw_version)
 Copyright:
+  Copyright (c) 2003, 2004 The Surfraw-Devel Team
+                           <surfraw-devel@lists.alioth.debian.org>
   Copyright (c) 2000-2001 Julian Assange <proff@iq.org>
   Copyright (c) 2001 Australian Institute for Collaborative Research
   Copyright (c) 2000 Melbourne Institute for Advanced Study
@@ -248,10 +278,19 @@ w3_parse_args () {
     w3_args=
     def SURFRAW_browser none
     def SURFRAW_browser_args none
+    defyn SURFRAW_quote_ifs yes
     do_help=0
     mode=unknown
     for arg in "$@"; do
-	w3_parse_option "$arg" || w3_args="$w3_args $arg"
+	    w3_parse_option "$arg"
+        if [ $? -eq 1 ]
+		then
+		    if ok SURFRAW_quote_ifs
+			then
+			    arg=`quote_ifs "$arg"`
+			fi
+		    w3_args="$w3_args $arg"
+		fi
     done
     if test $SURFRAW_browser = none; then
 	if ok SURFRAW_graphical && test -n "$DISPLAY"; then
@@ -296,7 +335,7 @@ w3_browse_url () {
 		fi
 	else
 		if test $SURFRAW_browser_args = "none"; then
-			$SURFRAW_browser "$@"
+				$SURFRAW_browser "$@"
 		else
 			$SURFRAW_browser $SURFRAW_browser_args "$@"
 		 fi
@@ -306,8 +345,83 @@ w3_browse_url () {
 #    ifno SURFRAW_quiet && echo "Thank you for supporting the Shell Users' Revolutionary Front Rage Against the Web"
 }
 
-case "$w3_argv0" in
-    surfraw) 
-        w3_config
-	w3_parse_option -elvi ;;
-esac
+quote () {
+	quoted=`echo "$1"|sed "s/'/'\\\\\''/g"`
+	echo "'$quoted'"
+}
+
+surfraw_usage() {
+	cat <<EOF
+Usage: `basename $0` [-help] [-elvi] elvis [elvioptions] [search terms]
+       `basename $0` [options] bookmark
+    If you wish to run the elvi directly, run "surfraw-update-path" to append
+	$elvidir to your \$PATH in your shell's config files.
+    See surfraw-update-path(1) for details
+Options:
+   -elvi  List elvi
+   -help  This help
+sr is an alias for surfraw
+EOF
+	w3_global_usage
+}
+
+if [ "$w3_argv0" = "surfraw" -o "$w3_argv0" = "sr" ]
+then
+	w3_config
+	opts=""
+	elvi=""
+	searchterms=""
+	for arg in "$@"
+	do
+	  # if it is an option
+	  if awk -v arg="$arg" 'BEGIN { if(arg ~ /^-/) { exit 0 } else { exit 1 } } ' 
+	  then
+		  # if option before elvi
+		  if [ -z "$elvi" ]
+		  then
+			  case "$arg" in
+				  -help*) surfraw_usage;         exit 0 ;;
+				  -\?)    surfraw_usage;         exit 0 ;;
+				  -elvi*)  w3_parse_option -elvi; exit 0 ;;
+			  esac
+		  fi
+		  if  [ -z "$opts" ]
+		  then
+			  opts="`quote "$arg"`"
+		  else
+			  opts="$opts `quote "$arg"`"
+		  fi
+	  elif [ -z "$elvi" ]
+	  then
+		  elvi="$arg"
+	  else
+		  if [ -z "$searchterms" ]
+		  then
+			  searchterms="`quote "$arg"`"
+		  else
+			  searchterms="$searchterms `quote "$arg"`"
+		  fi
+	  fi
+	done
+	if [ -z "$elvi" ]
+	then
+		surfraw_usage
+		exit 0
+	else
+		if [ -x "$elvidir/$elvi" ]
+		then
+ 			sh -c "$elvidir/$elvi $opts $searchterms"
+		else
+			bookmark=`bookmark_lookup $elvi`
+			if [ -n "$bookmark" ]
+			then
+				w3_parse_args "$opts"
+				w3_browse_url "$bookmark"
+			else
+				echo "`basename $0`: $elvi: No elvis or bookmark with that name"
+				surfraw_usage
+				exit 1
+			fi
+	   fi
+	fi
+fi
